'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings 自動保存機能"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("8cQ9BIFQa3hqcrxgbvPiOQ==")>  _
        Public Property _passwd_adm() As String
            Get
                Return CType(Me("_passwd_adm"),String)
            End Get
            Set
                Me("_passwd_adm") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("LuGAQ7IevCcWdl5ledQ3iw==")>  _
        Public Property _passwd_adm2() As String
            Get
                Return CType(Me("_passwd_adm2"),String)
            End Get
            Set
                Me("_passwd_adm2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("+fMH4XpJKNqwdZDUL0gFhg==")>  _
        Public Property _passwd_adm2_chg() As String
            Get
                Return CType(Me("_passwd_adm2_chg"),String)
            End Get
            Set
                Me("_passwd_adm2_chg") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property _sgresultsave_path() As String
            Get
                Return CType(Me("_sgresultsave_path"),String)
            End Get
            Set
                Me("_sgresultsave_path") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property _pfresultsave_path() As String
            Get
                Return CType(Me("_pfresultsave_path"),String)
            End Get
            Set
                Me("_pfresultsave_path") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Blue")>  _
        Public Property _angpkgraph_color() As Global.System.Drawing.Color
            Get
                Return CType(Me("_angpkgraph_color"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_angpkgraph_color") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Red")>  _
        Public Property _angdpgraph_color() As Global.System.Drawing.Color
            Get
                Return CType(Me("_angdpgraph_color"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_angdpgraph_color") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Green")>  _
        Public Property _ratpkdpgraph_color() As Global.System.Drawing.Color
            Get
                Return CType(Me("_ratpkdpgraph_color"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_ratpkdpgraph_color") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Red")>  _
        Public Property _ratmdcdgraph_color() As Global.System.Drawing.Color
            Get
                Return CType(Me("_ratmdcdgraph_color"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_ratmdcdgraph_color") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DarkGreen")>  _
        Public Property _velopkgraph_color() As Global.System.Drawing.Color
            Get
                Return CType(Me("_velopkgraph_color"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_velopkgraph_color") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Orange")>  _
        Public Property _velodpgraph_color() As Global.System.Drawing.Color
            Get
                Return CType(Me("_velodpgraph_color"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_velodpgraph_color") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Blue")>  _
        Public Property _velomdgraph_color() As Global.System.Drawing.Color
            Get
                Return CType(Me("_velomdgraph_color"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_velomdgraph_color") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Red")>  _
        Public Property _velocdgraph_color() As Global.System.Drawing.Color
            Get
                Return CType(Me("_velocdgraph_color"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_velocdgraph_color") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Blue")>  _
        Public Property _tsimdgraph_color() As Global.System.Drawing.Color
            Get
                Return CType(Me("_tsimdgraph_color"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_tsimdgraph_color") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Red")>  _
        Public Property _tsicdgraph_color() As Global.System.Drawing.Color
            Get
                Return CType(Me("_tsicdgraph_color"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_tsicdgraph_color") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property _ctresultsave_path() As String
            Get
                Return CType(Me("_ctresultsave_path"),String)
            End Get
            Set
                Me("_ctresultsave_path") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property _lgresultsave_path() As String
            Get
                Return CType(Me("_lgresultsave_path"),String)
            End Get
            Set
                Me("_lgresultsave_path") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public Property _printmargin_left() As Single
            Get
                Return CType(Me("_printmargin_left"),Single)
            End Get
            Set
                Me("_printmargin_left") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public Property _printmargin_right() As Single
            Get
                Return CType(Me("_printmargin_right"),Single)
            End Get
            Set
                Me("_printmargin_right") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public Property _printmargin_top() As Single
            Get
                Return CType(Me("_printmargin_top"),Single)
            End Get
            Set
                Me("_printmargin_top") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public Property _printmargin_bottom() As Single
            Get
                Return CType(Me("_printmargin_bottom"),Single)
            End Get
            Set
                Me("_printmargin_bottom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Brown")>  _
        Public Property _angpkgraph_color3() As Global.System.Drawing.Color
            Get
                Return CType(Me("_angpkgraph_color3"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_angpkgraph_color3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Green")>  _
        Public Property _angdpgraph_color3() As Global.System.Drawing.Color
            Get
                Return CType(Me("_angdpgraph_color3"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_angdpgraph_color3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Blue")>  _
        Public Property _ratpkdpgraph_color3() As Global.System.Drawing.Color
            Get
                Return CType(Me("_ratpkdpgraph_color3"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_ratpkdpgraph_color3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Brown")>  _
        Public Property _ratmdcdgraph_color3() As Global.System.Drawing.Color
            Get
                Return CType(Me("_ratmdcdgraph_color3"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_ratmdcdgraph_color3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Brown")>  _
        Public Property _velopkgraph_color3() As Global.System.Drawing.Color
            Get
                Return CType(Me("_velopkgraph_color3"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_velopkgraph_color3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Brown")>  _
        Public Property _velodpgraph_color3() As Global.System.Drawing.Color
            Get
                Return CType(Me("_velodpgraph_color3"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_velodpgraph_color3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Green")>  _
        Public Property _velomdgraph_color3() As Global.System.Drawing.Color
            Get
                Return CType(Me("_velomdgraph_color3"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_velomdgraph_color3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Green")>  _
        Public Property _velocdgraph_color3() As Global.System.Drawing.Color
            Get
                Return CType(Me("_velocdgraph_color3"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_velocdgraph_color3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Green")>  _
        Public Property _tsimdgraph_color3() As Global.System.Drawing.Color
            Get
                Return CType(Me("_tsimdgraph_color3"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_tsimdgraph_color3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Red")>  _
        Public Property _tsicdgraph_color3() As Global.System.Drawing.Color
            Get
                Return CType(Me("_tsicdgraph_color3"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_tsicdgraph_color3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property _printpreview() As Boolean
            Get
                Return CType(Me("_printpreview"),Boolean)
            End Get
            Set
                Me("_printpreview") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("50")>  _
        Public Property _test_count1() As Integer
            Get
                Return CType(Me("_test_count1"),Integer)
            End Get
            Set
                Me("_test_count1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("20")>  _
        Public Property _test_count2() As Integer
            Get
                Return CType(Me("_test_count2"),Integer)
            End Get
            Set
                Me("_test_count2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("50")>  _
        Public Property _test_count1_prf() As Integer
            Get
                Return CType(Me("_test_count1_prf"),Integer)
            End Get
            Set
                Me("_test_count1_prf") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("20")>  _
        Public Property _test_count2_prf() As Integer
            Get
                Return CType(Me("_test_count2_prf"),Integer)
            End Get
            Set
                Me("_test_count2_prf") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("50")>  _
        Public Property _test_count1_md() As Integer
            Get
                Return CType(Me("_test_count1_md"),Integer)
            End Get
            Set
                Me("_test_count1_md") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("20")>  _
        Public Property _test_count2_md() As Integer
            Get
                Return CType(Me("_test_count2_md"),Integer)
            End Get
            Set
                Me("_test_count2_md") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("400")>  _
        Public Property _timeout_time() As Integer
            Get
                Return CType(Me("_timeout_time"),Integer)
            End Get
            Set
                Me("_timeout_time") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property _cmd_timeout() As Integer
            Get
                Return CType(Me("_cmd_timeout"),Integer)
            End Get
            Set
                Me("_cmd_timeout") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5000")>  _
        Public Property _feed_timeout() As Integer
            Get
                Return CType(Me("_feed_timeout"),Integer)
            End Get
            Set
                Me("_feed_timeout") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Control")>  _
        Public Property _frm_MainForm_bc() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_MainForm_bc"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_MainForm_bc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Control")>  _
        Public Property _frm_MainMenu_bc() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_MainMenu_bc"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_MainMenu_bc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Control")>  _
        Public Property _frm_MainStatus_bc() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_MainStatus_bc"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_MainStatus_bc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Flat")>  _
        Public Property _frm_MainStatusBorder_stl() As Global.System.Windows.Forms.Border3DStyle
            Get
                Return CType(Me("_frm_MainStatusBorder_stl"),Global.System.Windows.Forms.Border3DStyle)
            End Get
            Set
                Me("_frm_MainStatusBorder_stl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Control")>  _
        Public Property _frm_MainButton_bc() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_MainButton_bc"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_MainButton_bc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ControlText")>  _
        Public Property _frm_MainButton_fc() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_MainButton_fc"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_MainButton_fc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ControlText")>  _
        Public Property _frm_MainForm_fc() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_MainForm_fc"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_MainForm_fc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ControlText")>  _
        Public Property _frm_MainMenu_fc() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_MainMenu_fc"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_MainMenu_fc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ControlText")>  _
        Public Property _frm_MainStatus_fc() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_MainStatus_fc"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_MainStatus_fc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DimGray")>  _
        Public Property _frm_MainLine_color() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_MainLine_color"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_MainLine_color") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Control")>  _
        Public Property _frm_MeasForm_bc() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_MeasForm_bc"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_MeasForm_bc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Control")>  _
        Public Property _frm_MeasMenu_bc() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_MeasMenu_bc"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_MeasMenu_bc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Control")>  _
        Public Property _frm_MeasStatus_bc() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_MeasStatus_bc"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_MeasStatus_bc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("White")>  _
        Public Property _frm_MeasGraph_bc() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_MeasGraph_bc"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_MeasGraph_bc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Flat")>  _
        Public Property _frm_MeasStatusBorder_stl() As Global.System.Windows.Forms.Border3DStyle
            Get
                Return CType(Me("_frm_MeasStatusBorder_stl"),Global.System.Windows.Forms.Border3DStyle)
            End Get
            Set
                Me("_frm_MeasStatusBorder_stl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ControlText")>  _
        Public Property _frm_MeasForm_fc() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_MeasForm_fc"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_MeasForm_fc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ControlText")>  _
        Public Property _frm_MeasMenu_fc() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_MeasMenu_fc"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_MeasMenu_fc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ControlText")>  _
        Public Property _frm_MeasStatus_fc() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_MeasStatus_fc"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_MeasStatus_fc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Control")>  _
        Public Property _frm_MeasButton_bc() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_MeasButton_bc"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_MeasButton_bc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ControlText")>  _
        Public Property _frm_MeasButton_fc() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_MeasButton_fc"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_MeasButton_fc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Yellow")>  _
        Public Property _frm_MeasuringButton_bc() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_MeasuringButton_bc"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_MeasuringButton_bc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ControlText")>  _
        Public Property _frm_MeasuringButton_fc() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_MeasuringButton_fc"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_MeasuringButton_fc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Blue")>  _
        Public Property _frm_MeasOldData_color() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_MeasOldData_color"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_MeasOldData_color") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Window")>  _
        Public Property _frm_MeasTextBox_bc() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_MeasTextBox_bc"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_MeasTextBox_bc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
        Public Property _frm_MeasCurData_color() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_MeasCurData_color"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_MeasCurData_color") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
        Public Property _frm_MeasGraphWaku_color() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_MeasGraphWaku_color"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_MeasGraphWaku_color") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Control")>  _
        Public Property _frm_PrfForm_bc() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_PrfForm_bc"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_PrfForm_bc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Control")>  _
        Public Property _frm_PrfMenu_bc() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_PrfMenu_bc"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_PrfMenu_bc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Control")>  _
        Public Property _frm_PrfStatus_bc() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_PrfStatus_bc"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_PrfStatus_bc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Control")>  _
        Public Property _frm_PrfButton_bc() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_PrfButton_bc"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_PrfButton_bc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ControlText")>  _
        Public Property _frm_PrfButton_fc() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_PrfButton_fc"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_PrfButton_fc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Yellow")>  _
        Public Property _frm_PrfMeasuringButton_bc() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_PrfMeasuringButton_bc"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_PrfMeasuringButton_bc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ControlText")>  _
        Public Property _frm_PrfMeasuringButton_fc() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_PrfMeasuringButton_fc"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_PrfMeasuringButton_fc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Blue")>  _
        Public Property _frm_PrfOldData_color() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_PrfOldData_color"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_PrfOldData_color") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
        Public Property _frm_PrfCurData_color() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_PrfCurData_color"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_PrfCurData_color") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
        Public Property _frm_PrfAvgData_color() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_PrfAvgData_color"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_PrfAvgData_color") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Window")>  _
        Public Property _frm_PrfTextBox_bc() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_PrfTextBox_bc"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_PrfTextBox_bc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
        Public Property _frm_PrfGraphWaku_color() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_PrfGraphWaku_color"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_PrfGraphWaku_color") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("White")>  _
        Public Property _frm_PrfGraph_bc() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_PrfGraph_bc"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_PrfGraph_bc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ControlText")>  _
        Public Property _frm_PrfForm_fc() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_PrfForm_fc"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_PrfForm_fc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ControlText")>  _
        Public Property _frm_PrfMenu_fc() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_PrfMenu_fc"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_PrfMenu_fc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ControlText")>  _
        Public Property _frm_PrfStatus_fc() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_PrfStatus_fc"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_PrfStatus_fc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Flat")>  _
        Public Property _frm_PrfStatusBorder_stl() As Global.System.Windows.Forms.Border3DStyle
            Get
                Return CType(Me("_frm_PrfStatusBorder_stl"),Global.System.Windows.Forms.Border3DStyle)
            End Get
            Set
                Me("_frm_PrfStatusBorder_stl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Control")>  _
        Public Property _frm_MeasMeasButton_bc() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_MeasMeasButton_bc"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_MeasMeasButton_bc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ControlText")>  _
        Public Property _frm_MeasMeasButton_fc() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_MeasMeasButton_fc"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_MeasMeasButton_fc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Control")>  _
        Public Property _frm_PrfMeasButton_bc() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_PrfMeasButton_bc"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_PrfMeasButton_bc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ControlText")>  _
        Public Property _frm_PrfMeasButton_fc() As Global.System.Drawing.Color
            Get
                Return CType(Me("_frm_PrfMeasButton_fc"),Global.System.Drawing.Color)
            End Get
            Set
                Me("_frm_PrfMeasButton_fc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property _printbc() As Boolean
            Get
                Return CType(Me("_printbc"),Boolean)
            End Get
            Set
                Me("_printbc") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.SST4500_1_0_0J.My.MySettings
            Get
                Return Global.SST4500_1_0_0J.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
